
project_id = "izzdyfrcxunfzlfgdjuv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[realtime]
enabled = true
port = 54329

[functions]
[functions.gemini-chat]
verify_jwt = false
[functions.listing-analyzer]
verify_jwt = false

